In [ ]:
!pip install ydata-profiling
import pandas as pd
import matplotlib.pyplot as plt
import pickle
from ydata_profiling import ProfileReport  # Import from ydata_profiling
import numpy as np

In [ ]:
df = pd.read_csv('advertising.csv')

In [ ]:
df

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [ ]:
df.head(10)

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9
5    8.7   48.9       75.0    7.2
6   57.5   32.8       23.5   11.8
7  120.2   19.6       11.6   13.2
8    8.6    2.1        1.0    4.8
9  199.8    2.6       21.2   15.6

In [ ]:
df.tail()

TV  Radio  Newspaper  Sales
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

In [ ]:
df.describe()

TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   15.130500
std     85.854236   14.846809   21.778621    5.283892
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   11.000000
50%    149.750000   22.900000   25.750000   16.000000
75%    218.825000   36.525000   45.100000   19.050000
max    296.400000   49.600000  114.000000   27.000000

In [ ]:
pf = ProfileReport(df)

In [ ]:
pf.to_widgets()

/usr/local/lib/python3.10/dist-packages/ydata_profiling/profile_report.py:528: UserWarning: Ipywidgets is not yet fully supported on Google Colab (https://github.com/googlecolab/colabtools/issues/60).As an alternative, you can use the HTML report. See the documentation for more information.
  warnings.warn(


Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
pf.to_file('test.html')

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
df

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [ ]:
x = df['TV']
x

0      230.1
1       44.5
2       17.2
3      151.5
4      180.8
       ...  
195     38.2
196     94.2
197    177.0
198    283.6
199    232.1
Name: TV, Length: 200, dtype: float64

In [ ]:
y = df['Sales']
y

0      22.1
1      10.4
2      12.0
3      16.5
4      17.9
       ... 
195     7.6
196    14.0
197    14.8
198    25.5
199    18.4
Name: Sales, Length: 200, dtype: float64

In [ ]:
from sklearn.linear_model import LinearRegression # Changed 'liner_model' to 'linear_model'

In [ ]:
# Create a LinearRegression object
linear = LinearRegression()

# Fit the model using your data
# Reshape x to a 2D array using reshape(-1, 1)
linear.fit(x.values.reshape(-1, 1), y)

LinearRegression()

In [ ]:
linear.intercept_

6.974821488229891

In [ ]:
linear.coef_

array([0.05546477])

In [ ]:
file = 'linear_reg.sav'
# Open the file in write binary ('wb') mode using 'with open(...)'
# This ensures the file is automatically closed even if errors occur.
with open(file, 'wb') as f:
    pickle.dump(linear, f)

In [ ]:
linear.predict([[45]])

array([9.47073616])

In [ ]:
l = [4, 4, 5, 5, 6, 7, 819, 98, 90]

In [ ]:
for i in l:
    print(linear.predict([[i]]))

[7.19668057]
[7.19668057]
[7.25214534]
[7.25214534]
[7.30761011]
[7.36307488]
[52.4004685]
[12.41036899]
[11.96665083]


In [ ]:
save_model = pickle.load(open(file, 'rb'))

In [ ]:
save_model.predict([[45]])

array([9.47073616])

In [ ]:
linear.score(x.values.reshape(-1, 1), y) # Reshape x to a 2

0.8121757029987414

Training: Finding optimal value of m,and c is known as training.