Phase 3: Advanced Topics in NumPy
Linear Algebra with NumPy
NumPy offers a comprehensive module, numpy.linalg, that provides tools to handle various linear algebra operations. Here’s a breakdown of key concepts starting with the dot product and matrix multiplication.

1. Dot Product and Matrix Multiplication
Dot Product
The dot product (or scalar product) is a linear algebra operation that involves multiplying two vectors element-wise and then summing the results. It's useful in many scenarios, such as calculating projections or determining angles between vectors.

Formula:

Dot Product
=
∑
𝑖
=
1
𝑛
(
𝑎
𝑖
⋅
𝑏
𝑖
)
Dot Product=
i=1
∑
n
​
 (a
i
​
 ⋅b
i
​
 )
where:

𝑎
a and
𝑏
b are two vectors.
𝑛
n is the number of elements in each vector.
Usage in NumPy
To compute the dot product between two vectors, you can use the numpy.dot() function or the @ operator.

In [1]:
import numpy as np

# Define two vectors
vector1= np.array([1, 2, 3, 4])
vector2 = np.array([5, 6, 7, 8])

# Calculate dot product
dot_product = np.dot(vector1, vector2)
print(dot_product)

70



Phase 3: Advanced Topics in NumPy
Linear Algebra with NumPy
NumPy offers a comprehensive module, numpy.linalg, that provides tools to handle various linear algebra operations. Here’s a breakdown of key concepts starting with the dot product and matrix multiplication.

1. Dot Product and Matrix Multiplication
Dot Product
The dot product (or scalar product) is a linear algebra operation that involves multiplying two vectors element-wise and then summing the results. It's useful in many scenarios, such as calculating projections or determining angles between vectors.

Formula:

Dot Product
=
∑
𝑖
=
1
𝑛
(
𝑎
𝑖
⋅
𝑏
𝑖
)
Dot Product=
i=1
∑
n
​
 (a
i
​
 ⋅b
i
​
 )
where:

𝑎
a and
𝑏
b are two vectors.
𝑛
n is the number of elements in each vector.
Usage in NumPy
To compute the dot product between two vectors, you can use the numpy.dot() function or the @ operator.

Example:

python
Copy code
import numpy as np

# Define two vectors
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Calculate dot product
dot_product = np.dot(vector1, vector2)
# or equivalently
dot_product_alt = vector1 @ vector2

print("Dot Product:", dot_product)  # Output: 32
Explanation:

Calculation:
(
1
∗
4
)
+
(
2
∗
5
)
+
(
3
∗
6
)
=
4
+
10
+
18
=
32
(1∗4)+(2∗5)+(3∗6)=4+10+18=32.
Matrix Multiplication
Matrix multiplication is a fundamental operation in linear algebra where two matrices are combined to form a new matrix. It's different from element-wise multiplication and follows specific rules.

Key Points:

For two matrices,
𝐴
A (of size
𝑚
×
𝑛
m×n) and
𝐵
B (of size
𝑛
×
𝑝
n×p), the resulting matrix
𝐶
=
𝐴
×
𝐵
C=A×B will have dimensions
𝑚
×
𝑝
m×p.
The number of columns in the first matrix must match the number of rows in the second.
Usage in NumPy
To perform matrix multiplication in NumPy, you can use:

numpy.dot()
@ operator
numpy.matmul() (alternative)

In [2]:
# Define two matrices
matrix1 = np.array([
    [1, 2],
    [3, 4]
])
matrix2 = np.array([
    [5, 6],
    [7, 8]
])

# Calcualte matrix multiplication
# result = np.matmul(matrix1, matrix2)
result = np.dot(matrix1, matrix2)
print("Matrix Multiplication Result:\n", result)

Matrix Multiplication Result:
 [[19 22]
 [43 50]]


2. Determinants, Inverses, and Eigenvalues
Determinant of a Matrix
The determinant is a scalar value that can be computed from a square matrix. It provides insights into the matrix's properties, such as whether the matrix is invertible (a matrix is invertible if its determinant is non-zero).

Usage in NumPy: numpy.linalg.det()

In [3]:
# Define a 2x2 matrix
matrix = np.array([
    [1, 2],
    [3, 4]
])

# Calculate the determinant
det = np.linalg.det(matrix)
print("Determinant:", det)

Determinant: -2.0000000000000004


Inverse of a Matrix
The inverse of a matrix
𝐴
A is another matrix
𝐴
−
1
A
−1
  such that
𝐴
⋅
𝐴
−
1
=
𝐼
A⋅A
−1
 =I, where
𝐼
I is the identity matrix. A matrix must be square and have a non-zero determinant to have an inverse.

Usage in NumPy: numpy.linalg.inv()

In [4]:
# Calculate the inverse of the matrix
inverse_matrix = np.linalg.inv(matrix)
print("Inverse of the Matrix:\n", inverse_matrix)

Inverse of the Matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


Eigenvalues and Eigenvectors
Eigenvalues and eigenvectors are critical in understanding the properties of a matrix. They are used in various domains like machine learning, data analysis, and physics.

Usage in NumPy: numpy.linalg.eig()

In [5]:
# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


3. Solving Linear Equations with numpy.linalg
To solve a system of linear equations, you can use the function numpy.linalg.solve(). Suppose you have a system:

𝐴
𝑥
=
𝐵
Ax=B
Where:

𝐴
A is a coefficient matrix.
𝐵
B is a result matrix (or vector).
𝑥
x is the solution vector.
Example:

In [6]:
# Coefficient matrix (A) and result vector (B)
A = np.array([
    [2, 1], [1, -1]
])
B = np.array([1, -1])

# Solve for x
x = np.linalg.solve(A, B)
print("Solution for x:", x)

Solution for x: [0. 1.]


Exercise 6: Performing Matrix Operations
Perform matrix multiplication between two matrices.
Calculate the determinant of the resulting matrix.
Solve a system of linear equations.

In [7]:
# Step 1: Matrix Multiplication
matrix1 = np.array([
    [1, 2],
    [3, 4]
])
matrix2 = np.array([
    [5, 6],
    [7, 8]
])

mul_result = matrix1 @ matrix2

# Step 2: Calculate the determinant
det_result = np.linalg.det(result)

# Step 3: Solve a system of linear equations
A = np.array([
    [3, 2],
    [1, 2]
])

B = np.array([5, 6])
solution = np.linalg.solve(A, B)

# Printing the results
print("Matrix multiplication result:\n", mul_result)
print("Determinant of the resulting matrix:", det_result)
print("Solution to the system of Equations:", solution)

Matrix multiplication result:
 [[19 22]
 [43 50]]
Determinant of the resulting matrix: 4.000000000000008
Solution to the system of Equations: [-0.5   3.25]


4. Advanced Array Functions
Sorting Arrays with numpy.sort
You can sort arrays along any axis using the numpy.sort() function. Sorting is helpful when dealing with ordered data or performing analyses like finding medians or ranks.

In [8]:
array = np.array([5, 2, 9, 1, 5, 6])
sorted_array = np.sort(array)
print("Sorted array:", sorted_array)

Sorted array: [1 2 5 5 6 9]


Searching within Arrays
numpy.argmax(): Finds the index of the maximum value.
numpy.argmin(): Finds the index of the minimum value.
numpy.where(): Returns the indices of elements that satisfy a given condition.

In [9]:
array = np.array([5, 2, 9, 1, 5, 6])

# Get index of max and min
max_index = np.argmax(array)
min_index = np.argmin(array)

# Use where to find elements greater than 5
indices_greater_than_five = np.where(array > 5)

# Printing the results
print("Index of Max Value:", max_index)
print("Index of min value:", min_index)
print("Indices of Elemnets > 5:", indices_greater_than_five)

Index of Max Value: 2
Index of min value: 3
Indices of Elemnets > 5: (array([2, 5]),)


Mini-Project 2: NumPy-Based Recommendation System
Objective: Create a simple recommendation system using NumPy. Suppose you have a dataset with product ratings, and you want to recommend products based on user similarity.

Steps:

Create a matrix where rows represent users and columns represent products, with ratings as elements.
Compute similarity between users using the dot product.
Recommend products that similar users liked.

In [10]:
# Sample ratings matrix (users x products)
ratings = np.array([
    [5, 3, 0, 1],  # User 1
    [4, 0, 0, 1],  # User 2
    [1, 1, 0, 5],  # User 3
    [0, 0, 5, 4],  # User 4
    [3, 3, 4, 0],  # User 5
])

# Calculate user similarity using dot product
similarity = np.dot(ratings, ratings.T)

# Recommend a product to User 1 based on similarity to User 5
user_index = 0  # User 1
similar_user_index = 4  # User 5
recommendations = ratings[similar_user_index, ratings[user_index] == 0]

print("Recommendations for User 1 based on User 5:", recommendations)


Recommendations for User 1 based on User 5: [4]
